AWSTemplateFormatVersion: 2010-09-09
Description: Dynamic References (ssm, ssm-secure, secretsmanager)

Resources:
  MyParameter01:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: MyParameter01
      Type: String
      Value: MyParameter01Value
      Description: "SSM Parameter for testing."
      Tags:
        "Environment": "DEV"

  MySecret01:
    Type: "AWS::SecretsManager::Secret"
    Properties:
      Name: MySecret01
      Description: "This secret has a dynamically generated secret password."
      GenerateSecretString:
        SecretStringTemplate: '{"username": "test-user"}'
        GenerateStringKey: "password"
        PasswordLength: 30
        ExcludeCharacters: '"@/\'
      Tags:
        - Key: AppName
          Value: AppA

# Outputs:
#   # `ssm:MyParameter01` must exist before being referenced
#   # comment the following on "create", then uncomment on "update".
#   MyParameter01Value:
#     Value: "{{resolve:ssm:MyParameter01:1}}"
#     Export:
#       Name: !Join [":", [!Ref "AWS::StackName", "MyParameter01Value"]]

#   MySecret01Value:
#     Value: "{{resolve:secretsmanager:MySecret01:SecretString:password}}"
#     Export:
#       Name: !Join [":", [!Ref "AWS::StackName", "MySecret01Value"]]
